import React from 'react';
import { Role, Message } from '../types';
import { User, Copy, Check, Cpu, Link as LinkIcon, Image as ImageIcon, Terminal } from 'lucide-react';

const FormattedText: React.FC<{ text: string }> = ({ text }) => {
  const parts = text.split(/(```[\s\S]*?```)/g);

  return (
    <div className="markdown-body text-sm md:text-base leading-relaxed">
      {parts.map((part, index) => {
        if (part.startsWith('```') && part.endsWith('```')) {
          const content = part.slice(3, -3).replace(/^[a-z]+\n/, '');
          return (
            <pre key={index} className="my-4 rounded-lg bg-black/80 p-4 overflow-x-auto border border-white/10 shadow-inner relative group">
              <code className="font-mono text-gray-200">{content}</code>
            </pre>
          );
        }
        return part.split('\n\n').map((paragraph, pIndex) => (
            <p key={`${index}-${pIndex}`} className="mb-3 last:mb-0 whitespace-pre-wrap">
                {paragraph.split(/(\*\*.*?\*\*)/g).map((seg, sIndex) => 
                    seg.startsWith('**') && seg.endsWith('**') 
                    ? <strong key={sIndex} className="font-bold text-current opacity-90">{seg.slice(2, -2)}</strong> 
                    : seg
                )}
            </p>
        ));
      })}
    </div>
  );
};

interface MessageBubbleProps {
  message: Message;
  themeColor: string;
}

export const MessageBubble: React.FC<MessageBubbleProps> = ({ message, themeColor }) => {
  const isUser = message.role === Role.User;
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(message.text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Dynamic style classes based on theme
  const botBgClass = themeColor === 'cyan' 
    ? 'bg-gradient-to-br from-cyan-50 to-white border-cyan-100'
    : 'bg-gradient-to-br from-red-50 to-white border-red-100';
  
  const avatarBgClass = themeColor === 'cyan'
    ? 'bg-gradient-to-br from-cyan-600 to-blue-900 border-cyan-500'
    : 'bg-gradient-to-br from-red-600 to-rose-900 border-red-500';

  return (
    <div className={`flex w-full mb-6 animate-float ${isUser ? 'justify-end' : 'justify-start'}`} style={{ animationDuration: '0s' }}>
      <div className={`flex flex-col max-w-[90%] md:max-w-[80%] lg:max-w-[70%] gap-2 ${isUser ? 'items-end' : 'items-start'}`}>
        
        <div className={`flex gap-4 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
            {/* Avatar */}
            <div className={`flex-shrink-0 w-10 h-10 rounded-xl flex items-center justify-center shadow-lg border-2 ${
            isUser 
                ? 'bg-white border-gray-100 text-gray-600' 
                : `${avatarBgClass} text-white shadow-neon`
            }`}>
            {isUser ? <User size={20} /> : <Cpu size={20} />}
            </div>

            {/* Bubble */}
            <div className={`group relative px-6 py-5 rounded-3xl shadow-sm border backdrop-blur-sm ${
            isUser 
                ? 'bg-white/90 border-white text-gray-800 rounded-tr-sm shadow-glass' 
                : `${botBgClass} text-gray-900 rounded-tl-sm shadow-lg`
            }`}>
            
            {/* Decorative corner accent for Bot */}
            {!isUser && <div className={`absolute top-0 left-0 w-3 h-3 border-t border-l rounded-tl-sm opacity-50 ${themeColor === 'cyan' ? 'border-cyan-400' : 'border-red-400'}`}></div>}
            
            {/* User Attachment */}
            {message.attachment && (
                <div className="mb-3 rounded-lg overflow-hidden border border-gray-200 shadow-sm">
                    {message.attachment.mimeType.startsWith('image/') ? (
                        <img src={`data:${message.attachment.mimeType};base64,${message.attachment.data}`} alt="Attachment" className="max-w-full h-auto max-h-64 object-cover" />
                    ) : (
                        <div className="p-3 bg-gray-50 flex items-center gap-2 text-sm font-mono text-gray-600">
                            <ImageIcon size={16} />
                            <span>Attachment</span>
                        </div>
                    )}
                </div>
            )}

            {/* Generated Image */}
            {message.generatedImage && (
                <div className="mb-4 rounded-xl overflow-hidden shadow-lg border border-white/50 group-hover:shadow-neon transition-shadow">
                     <img src={`data:image/jpeg;base64,${message.generatedImage}`} alt="Generated" className="w-full h-auto" />
                     <div className="bg-black/50 text-white text-[10px] p-1 px-2 absolute top-2 right-2 rounded backdrop-blur-md">Generated by Imagen</div>
                </div>
            )}

            {message.isThinking ? (
                <div className="flex items-center gap-2 h-6">
                <span className={`w-2 h-2 rounded-full animate-pulse ${themeColor === 'cyan' ? 'bg-cyan-500' : 'bg-red-500'}`} style={{ animationDelay: '0ms' }}></span>
                <span className={`w-2 h-2 rounded-full animate-pulse ${themeColor === 'cyan' ? 'bg-cyan-500' : 'bg-red-500'}`} style={{ animationDelay: '150ms' }}></span>
                <span className={`w-2 h-2 rounded-full animate-pulse ${themeColor === 'cyan' ? 'bg-cyan-500' : 'bg-red-500'}`} style={{ animationDelay: '300ms' }}></span>
                </div>
            ) : (
                <>
                <FormattedText text={message.text} />
                
                {/* Code Execution Result Display */}
                {message.executableCode && (
                    <div className="mt-3 p-3 bg-gray-900 rounded-lg border-l-4 border-yellow-500 font-mono text-xs text-gray-300">
                        <div className="flex items-center gap-2 mb-1 text-yellow-500"><Terminal size={12}/> Executing Code...</div>
                        <div className="opacity-70 truncate">{message.executableCode.code}</div>
                    </div>
                )}
                {message.codeExecutionResult && (
                     <div className="mt-2 p-3 bg-gray-900 rounded-lg border-l-4 border-green-500 font-mono text-xs text-green-300">
                        <div className="mb-1 text-green-500 font-bold">Result:</div>
                        <pre className="whitespace-pre-wrap">{message.codeExecutionResult.output}</pre>
                    </div>
                )}

                {/* Actions */}
                {!isUser && (
                    <div className="absolute -bottom-8 left-0 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-2 pl-2">
                    <button 
                        onClick={handleCopy}
                        className={`text-gray-400 transition-colors p-1.5 bg-white rounded-full shadow-sm border border-gray-100 ${themeColor === 'cyan' ? 'hover:text-cyan-600' : 'hover:text-red-600'}`}
                        title="Copy response"
                    >
                        {copied ? <Check size={12} /> : <Copy size={12} />}
                    </button>
                    </div>
                )}
                </>
            )}
            </div>
        </div>
        
        {/* Grounding Chips */}
        {message.groundingChunks && message.groundingChunks.length > 0 && (
            <div className="flex flex-wrap gap-2 pl-14">
                {message.groundingChunks.map((chunk, idx) => (
                    chunk.web?.uri && (
                        <a 
                            key={idx} 
                            href={chunk.web.uri} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className={`text-[10px] flex items-center gap-1 px-2 py-1 rounded-full bg-white/50 border border-gray-200 hover:bg-white transition-colors ${themeColor === 'cyan' ? 'text-cyan-700 hover:border-cyan-300' : 'text-red-700 hover:border-red-300'}`}
                        >
                            <LinkIcon size={10} />
                            <span className="truncate max-w-[150px]">{chunk.web.title || 'Source'}</span>
                        </a>
                    )
                ))}
            </div>
        )}
      </div>
    </div>
  );
};